version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_USER: "iam_program"
      POSTGRES_PASSWORD: "ETqdG59zTQ4zTrCV"
      POSTGRES_DB: "iam"
    networks:
      - iam
  app:
    image: "iam:latest"
    ports:
      - "8080:8080"
    networks:
      - iam
    volumes:
      - ../config:/app/deployments/config
    environment:
      CONFIG_NAME: app.deploy
networks:
  iam:
    name: iam