[log]
env = "local"
app_id = "iam"
debug = true
level = 0

[database]
[database.read]
debug = true
host = "mysql"
user = "iam_program"
password = "ETqdG59zTQ4zTrCV"
port = 3306
name = "iam"
type = "mysql"

[database.write]
debug = true
host = "mysql"
user = "iam_program"
password = "ETqdG59zTQ4zTrCV"
port = 3306
name = "iam"
type = "mysql"

[http]
mode = "debug"
port = ":8080"
dump = false

[redis]
addr = "redis:6379"