[log]
env = "local"
app = "iam"
debug = true
level = 0

[database]
[database.conn]
debug = true
host = "127.0.0.1"
user = "iam_program"
password = "ETqdG59zTQ4zTrCV"
port = 8081
name = "iam"
type = "postgres"

[http]
mode = "debug"
port = ":8080"
dump = true

[grpc]
port = ":9090"