[log]
env = "local"
app = "iam"
debug = false
level = 0

[database]
[database.conn]
debug = false
host = "127.0.0.1"
user = "iam_program"
password = "ETqdG59zTQ4zTrCV"
port = 8081
name = "iam"
type = "postgres"

[http]
mode = "release"
port = ":8080"

[grpc]
port = ":9090"