// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: pb/identity/identity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SigninReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SigninReq) Reset() {
	*x = SigninReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_identity_identity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigninReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninReq) ProtoMessage() {}

func (x *SigninReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_identity_identity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninReq.ProtoReflect.Descriptor instead.
func (*SigninReq) Descriptor() ([]byte, []int) {
	return file_pb_identity_identity_proto_rawDescGZIP(), []int{0}
}

type SigninResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SigninResp) Reset() {
	*x = SigninResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_identity_identity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigninResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninResp) ProtoMessage() {}

func (x *SigninResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_identity_identity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninResp.ProtoReflect.Descriptor instead.
func (*SigninResp) Descriptor() ([]byte, []int) {
	return file_pb_identity_identity_proto_rawDescGZIP(), []int{1}
}

type SignupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignupReq) Reset() {
	*x = SignupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_identity_identity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupReq) ProtoMessage() {}

func (x *SignupReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_identity_identity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupReq.ProtoReflect.Descriptor instead.
func (*SignupReq) Descriptor() ([]byte, []int) {
	return file_pb_identity_identity_proto_rawDescGZIP(), []int{2}
}

type SignupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignupResp) Reset() {
	*x = SignupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_identity_identity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResp) ProtoMessage() {}

func (x *SignupResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_identity_identity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResp.ProtoReflect.Descriptor instead.
func (*SignupResp) Descriptor() ([]byte, []int) {
	return file_pb_identity_identity_proto_rawDescGZIP(), []int{3}
}

var File_pb_identity_identity_proto protoreflect.FileDescriptor

var file_pb_identity_identity_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x32, 0x57, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12,
	0x0a, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e,
	0x75, 0x70, 0x12, 0x0a, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0b,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_identity_identity_proto_rawDescOnce sync.Once
	file_pb_identity_identity_proto_rawDescData = file_pb_identity_identity_proto_rawDesc
)

func file_pb_identity_identity_proto_rawDescGZIP() []byte {
	file_pb_identity_identity_proto_rawDescOnce.Do(func() {
		file_pb_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_identity_identity_proto_rawDescData)
	})
	return file_pb_identity_identity_proto_rawDescData
}

var file_pb_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_identity_identity_proto_goTypes = []interface{}{
	(*SigninReq)(nil),  // 0: SigninReq
	(*SigninResp)(nil), // 1: SigninResp
	(*SignupReq)(nil),  // 2: SignupReq
	(*SignupResp)(nil), // 3: SignupResp
}
var file_pb_identity_identity_proto_depIdxs = []int32{
	0, // 0: IdentityService.Signin:input_type -> SigninReq
	2, // 1: IdentityService.Signup:input_type -> SignupReq
	1, // 2: IdentityService.Signin:output_type -> SigninResp
	3, // 3: IdentityService.Signup:output_type -> SignupResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_identity_identity_proto_init() }
func file_pb_identity_identity_proto_init() {
	if File_pb_identity_identity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_identity_identity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigninReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_identity_identity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigninResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_identity_identity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_identity_identity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_identity_identity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_identity_identity_proto_goTypes,
		DependencyIndexes: file_pb_identity_identity_proto_depIdxs,
		MessageInfos:      file_pb_identity_identity_proto_msgTypes,
	}.Build()
	File_pb_identity_identity_proto = out.File
	file_pb_identity_identity_proto_rawDesc = nil
	file_pb_identity_identity_proto_goTypes = nil
	file_pb_identity_identity_proto_depIdxs = nil
}
